// ─── Script Template: Hut of the Magi / Eye of the Magi (issue #149) ──────────
// Real HoMM3 mechanic (verified via web research: heroes.thelazy.net,
// mightandmagic.fandom.com): visiting ANY Hut of the Magi reveals a ~10-tile
// fog-of-war radius around EVERY Eye of the Magi on the map — a many-to-many
// broadcast, not a strict pair. The Eye itself is never interacted with; it's
// purely a reveal target.
//
// Olden Era has no native Hut/Eye object types, so this template lets the map
// author pick which already-placed objects play each role, then generates one
// hidden Quest with one SubQuest containing one Trigger per picked Hut. Each
// trigger's condition fires when that Hut is interacted with
// (ObjectInteractionAfter); its actions reveal fog of war (RevealFogOfWar)
// around every picked Eye's node index.
//
// Node indices are baked in as literal numbers at generation time —
// RevealFogOfWar's params are a plain [nodeIndex, radius] string pair, not a
// mapEntity reference (see src/schema/actions.ts) — so there is no live
// binding back to the picked SIDs. Moving a Hut/Eye afterward requires
// re-running the template.

import type { Quest, SubQuest, Trigger } from '@/types/scenario'
import type { MapContext } from '@/types/map-context'
import type { ScriptTemplateDef, ScriptTemplateInput } from '@/types/script-template'
import { resolveNodeForSid } from './resolve-node'
import { uniqueSid } from '@/store/useScenarioStore'

const GENERATED_COMMENT = 'Generated by Script Template: Hut of the Magi (v1)'
const BASE_QUEST_SID = 'script_hut_of_the_magi'
const DEFAULT_RADIUS = 10

function validate(input: ScriptTemplateInput, mapContext: MapContext | null): string[] {
  const errors: string[] = []
  const huts = input.slots.huts ?? []
  const eyes = input.slots.eyes ?? []

  if (huts.length === 0) errors.push('Pick at least one Hut of the Magi object.')
  if (eyes.length === 0) errors.push('Pick at least one Eye of the Magi object.')

  if (!mapContext) {
    if (huts.length > 0 || eyes.length > 0) {
      errors.push('Load a .map file to resolve object positions before generating.')
    }
    return errors
  }

  for (const sid of eyes) {
    if (resolveNodeForSid(sid, mapContext) === undefined) {
      errors.push(`Could not resolve a map position for Eye object "${sid}" — is it placed and named on the loaded map?`)
    }
  }

  return errors
}

function generate(
  input: ScriptTemplateInput,
  mapContext: MapContext | null,
  existingSids: { quests: string[]; counters: string[] },
) {
  // validate() already guarantees mapContext is non-null whenever huts/eyes are
  // non-empty — this guard just keeps the type honest for the shared interface.
  if (!mapContext) throw new Error('Hut of the Magi requires a loaded .map file.')

  const huts = input.slots.huts ?? []
  const eyes = input.slots.eyes ?? []
  const radius = input.params.radius ?? DEFAULT_RADIUS

  const eyeNodes = eyes
    .map((sid) => resolveNodeForSid(sid, mapContext))
    .filter((node): node is number => node !== undefined)

  const triggers: Trigger[] = huts.map((hutSid) => ({
    conditionsLogic: 'And',
    conditions: [{ c: 'ObjectInteractionAfter', p: [hutSid, ''] }],
    actions: eyeNodes.map((node) => ({ a: 'RevealFogOfWar', p: [String(node), String(radius)] })),
  }))

  const subQuest: SubQuest = {
    sid: '1',
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    triggers,
  }

  const sid = existingSids.quests.includes(BASE_QUEST_SID)
    ? uniqueSid(BASE_QUEST_SID, existingSids.quests)
    : BASE_QUEST_SID

  const quest: Quest = {
    sid,
    hidden: true,
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    subQuests: [subQuest],
  }

  return { quest }
}

export const hutOfTheMagiTemplate: ScriptTemplateDef = {
  id: 'hut-of-the-magi',
  name: 'Hut of the Magi / Eye of the Magi',
  description:
    'Visiting any Hut reveals the fog of war around every Eye on the map — the classic HoMM3 scouting pair.',
  category: 'Classic HoMM3 Objects',
  slots: [
    {
      id: 'huts',
      label: 'Huts of the Magi',
      description: 'Objects that, when visited, reveal the area around every Eye below.',
      cardinality: 'many',
    },
    {
      id: 'eyes',
      label: 'Eyes of the Magi',
      description: 'Objects whose surrounding fog of war gets revealed. Never interacted with directly.',
      cardinality: 'many',
    },
  ],
  params: [
    { id: 'radius', label: 'Reveal radius', defaultValue: DEFAULT_RADIUS, min: 1, max: 50 },
  ],
  validate,
  generate,
}
