// ─── Script Template: Key/Lock (Keymaster's Tent / Border Guard) (issue #149) ─
// Real HoMM3 mechanic (verified via web research: heroes.thelazy.net,
// mightandmagic.fandom.com): visiting a colored Keymaster's Tent permanently
// lets that player's heroes pass every Border Gate/Guard of the same color,
// map-wide, for the rest of the game. Generalized here beyond the 8 fixed
// colors: pick any number of Tents and Guards under one human-named key id,
// so a map author can create as many independent key/lock pairs as needed.
//
// Every primitive this needs exists cleanly in this engine's vocabulary —
// see the plan for the full verification. Two notable points carried over
// from that research:
// - This is the first script template to use `Trigger.repeat: true`: a
//   Guard must keep blocking every unkeyed hero, repeatedly, not just once
//   (Hut of the Magi / Seer's Hut only ever needed the default one-shot
//   behavior). The AND-combined counter check on both the unlock and block
//   triggers is what keeps them mutually exclusive on any single visit.
// - `Counter` has no per-player dimension in this engine, so the generated
//   key flag is global: once ANY player's hero visits a Tent, ALL players'
//   heroes can pass the matching Guards — a real divergence from HoMM3's
//   per-player tracking, accepted as low-impact for this template's stated
//   audience (campaign creators, typically single-human-player maps).

import type { Quest, SubQuest, Trigger, Action } from '@/types/scenario'
import type { ScriptTemplateDef, ScriptTemplateInput } from '@/types/script-template'
import type { MapContext } from '@/types/map-context'
import { uniqueSid } from '@/store/useScenarioStore'
import { resolveNodeForSid } from './resolve-node'

const GENERATED_COMMENT = 'Generated by Script Template: Key/Lock (v1)'
const BASE_QUEST_SID = 'script_key_lock'

function field(input: ScriptTemplateInput, key: string): string {
  return (input.fields[key] ?? '').trim()
}

function validate(input: ScriptTemplateInput, mapContext: MapContext | null, existingCounterSids: string[]): string[] {
  const errors: string[] = []
  const tents = (input.slots.tents ?? []).filter((s) => s.trim() !== '')
  const guards = (input.slots.guards ?? []).filter((s) => s.trim() !== '')
  const keyCounterSid = field(input, 'keyCounterSid')
  const vfxSid = field(input, 'vfxSid')

  if (tents.length === 0) errors.push('Pick at least one Tent object.')
  if (guards.length === 0) errors.push('Pick at least one Guard object.')

  if (!keyCounterSid) {
    errors.push('Name the key (this becomes a new counter tracking whether it has been found).')
  } else if (existingCounterSids.includes(keyCounterSid)) {
    errors.push(`"${keyCounterSid}" is already used by another counter — pick a different key name.`)
  }

  if (vfxSid && !mapContext) {
    errors.push('Load a .map file to resolve Tent positions for the visual effect (or clear the VFX field to skip it).')
  }
  if (vfxSid && mapContext) {
    for (const sid of tents) {
      if (resolveNodeForSid(sid, mapContext) === undefined) {
        errors.push(`Could not resolve a map position for Tent object "${sid}" — needed to place the visual effect.`)
      }
    }
  }

  return errors
}

function generate(
  input: ScriptTemplateInput,
  mapContext: MapContext | null,
  existingSids: { quests: string[]; counters: string[] },
) {
  const tents = (input.slots.tents ?? []).filter((s) => s.trim() !== '')
  const guards = (input.slots.guards ?? []).filter((s) => s.trim() !== '')
  const keyCounterSid = field(input, 'keyCounterSid')
  const tentDialogSid = field(input, 'tentDialogSid')
  const guardBlockDialogSid = field(input, 'guardBlockDialogSid')
  const vfxSid = field(input, 'vfxSid')

  const triggers: Trigger[] = []

  for (const tentSid of tents) {
    const actions: Action[] = [{ a: 'CounterSet', p: [keyCounterSid, '1'] }]
    if (vfxSid && mapContext) {
      const node = resolveNodeForSid(tentSid, mapContext)
      if (node !== undefined) {
        actions.push({ a: 'CreateVFX', p: [vfxSid, String(node), 'false', 'true'] })
      }
    }
    if (tentDialogSid) actions.push({ a: 'Dialog', p: [tentDialogSid] })

    triggers.push({
      conditions: [{ c: 'ObjectInteractionAfter', p: [tentSid, ''] }],
      actions,
    })
  }

  for (const guardSid of guards) {
    triggers.push({
      conditionsLogic: 'And',
      conditions: [
        { c: 'ObjectInteractionAfter', p: [guardSid, ''] },
        { c: 'Counter', p: [keyCounterSid, '=', '1'] },
      ],
      actions: [{ a: 'DeleteEntity', p: [guardSid] }],
    })

    const blockActions: Action[] = []
    if (guardBlockDialogSid) blockActions.push({ a: 'Dialog', p: [guardBlockDialogSid] })
    blockActions.push({ a: 'BreakInterruptions', p: [] })
    blockActions.push({ a: 'StepBack', p: [] })

    triggers.push({
      conditionsLogic: 'And',
      repeat: true,
      conditions: [
        { c: 'ObjectInteractionAfter', p: [guardSid, ''] },
        { c: 'Counter', p: [keyCounterSid, '=', '0'] },
      ],
      actions: blockActions,
    })
  }

  const subQuest: SubQuest = {
    sid: '1',
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    triggers,
  }

  const sid = existingSids.quests.includes(BASE_QUEST_SID)
    ? uniqueSid(BASE_QUEST_SID, existingSids.quests)
    : BASE_QUEST_SID

  const quest: Quest = {
    sid,
    hidden: true,
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    subQuests: [subQuest],
  }

  return { quest, counters: [{ sid: keyCounterSid, value: 0 }] }
}

export const keyLockTemplate: ScriptTemplateDef = {
  id: 'key-lock',
  name: "Keymaster's Tent / Border Guard",
  description:
    "Visiting any Tent unlocks every Guard sharing its key, permanently — the classic HoMM3 colored gate mechanic, generalized to as many independent keys as you need.",
  category: 'Classic HoMM3 Objects',
  slots: [
    {
      id: 'tents',
      label: 'Tent objects',
      description: 'Visiting any of these sets the key as found.',
      cardinality: 'many',
    },
    {
      id: 'guards',
      label: 'Guard objects',
      description: 'Blocks passage until the key is found, then is removed permanently.',
      cardinality: 'many',
    },
  ],
  stringParams: [
    { id: 'keyCounterSid', label: 'Key name (new counter)', placeholder: 'e.g. red_key_found', required: true },
    { id: 'tentDialogSid', label: 'Tent visit dialog (optional)', placeholder: 'Existing dialog SID' },
    { id: 'guardBlockDialogSid', label: 'Guard block dialog (optional)', placeholder: 'Existing dialog SID' },
    { id: 'vfxSid', label: 'Tent activation VFX (optional)', placeholder: 'e.g. fx_map_fire' },
  ],
  validate: (input, mapContext, existingSids) => validate(input, mapContext, existingSids.counters),
  generate,
}
