// ─── Script Template: Seer's Hut (issue #149) ─────────────────────────────────
// Real HoMM3 mechanic (verified via web research: heroes.thelazy.net,
// mightandmagic.fandom.com, and community discussion of the exact quest/reward
// vocabulary added in Armageddon's Blade): a hero visits the Seer's Hut and is
// offered a quest. Returning once the requirement is met grants a reward; for
// "bring X" style requirements (resources, artifacts) the brought items are
// CONSUMED as payment — level/skill/kill-based requirements consume nothing.
// The quest completes once, for whichever player's hero fulfills it first.
//
// This app's condition vocabulary models "requirement met" as a persistent,
// re-checkable state (ResCounter/ItemOwnSide/etc. — see CONDITION_REGISTRY),
// not a one-off event, so AND-combining the hut-visit condition with the
// requirement condition in one trigger correctly expresses "hero walks in
// AFTER already meeting the requirement" — matching real Seer's Hut behavior
// (you must physically return to collect; satisfying the condition remotely
// doesn't auto-grant the reward). See src/schema/conditions.ts/actions.ts for
// the exact building blocks reused here.
//
// Scope decisions, made after checking exactly what this engine's vocabulary
// supports (not guessed — see the exploration that produced this file):
// - Requirement types offered: Resources, Artifact, Defeat Monster, Defeat
//   Hero, Primary Skill. "Hero level >= N" is NOT offered — there is no
//   native level-check condition anywhere in this engine's vocabulary (only
//   TutorialLevelUp, a one-shot trip-wire with no threshold), so it can't be
//   built without inventing behavior that doesn't exist.
// - "Bring Creatures" is NOT offered as a requirement type: the only
//   ownership check scoped to a single hero (UnitOwnHero) requires a fixed,
//   explicit Hero SID with no "any/currently-interacting hero" option (unlike
//   ObjectInteractionAfter's hero param, HeroStat's hero param, or
//   GiveItemHero/GiveStatsHero's hero param, which all support leaving the
//   hero blank to mean "whichever hero is involved"). Offering it would mean
//   either silently restricting the quest to one named hero (surprising) or
//   producing a condition that can never fire for other heroes.
// - Reward types offered: Resources, Artifact, Primary Skill boost. Give
//   Experience is NOT offered for the same reason — GiveExpHero's Hero SID
//   param is required, not blank-able, so it can't target "whichever hero
//   turned in the quest" generically.
// - No "hint message on an incomplete visit" — Dialog actions only ever
//   reference an existing DialogFlow by sid (there's no inline-text variant),
//   so an optional "offer" dialog on first visit is supported (user picks an
//   existing dialog sid, authored separately in the Dialog Editor), but a
//   dynamic "you haven't met the requirement yet" hint is out of scope — it
//   would require negating a condition, which this engine's trigger model
//   (AND/OR over a flat condition list) doesn't expose.

import { Fragment } from 'react'
import type { Quest, SubQuest, Trigger, Condition, Action } from '@/types/scenario'
import type { ScriptTemplateDef, ScriptTemplateInput, ScriptTemplateFieldsProps } from '@/types/script-template'
import { uniqueSid } from '@/store/useScenarioStore'
import { BASIC_RESOURCE_IDS } from '@/lib/resources'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select'
import MapEntityCombobox from '@/components/common/MapEntityCombobox'
import EntityCombobox from '@/components/common/EntityCombobox'

const GENERATED_COMMENT = "Generated by Script Template: Seer's Hut (v1)"
const BASE_QUEST_SID = 'script_seers_hut'

const PRIMARY_SKILLS = [
  { id: 'offence', label: 'Attack' },
  { id: 'defence', label: 'Defense' },
  { id: 'spellPower', label: 'Spell Power' },
  { id: 'intelligence', label: 'Knowledge' },
]

type RequirementType = 'resources' | 'artifact' | 'defeatMonster' | 'defeatHero' | 'skill'
type RewardType = 'resources' | 'artifact' | 'skill'

const REQUIREMENT_OPTIONS: { id: RequirementType; label: string }[] = [
  { id: 'resources', label: 'Bring Resources' },
  { id: 'artifact', label: 'Bring Artifact' },
  { id: 'defeatMonster', label: 'Defeat a Monster' },
  { id: 'defeatHero', label: 'Defeat a Hero' },
  { id: 'skill', label: 'Reach a Primary Skill Level' },
]

const REWARD_OPTIONS: { id: RewardType; label: string }[] = [
  { id: 'resources', label: 'Give Resources' },
  { id: 'artifact', label: 'Give Artifact' },
  { id: 'skill', label: 'Boost a Primary Skill' },
]

function field(input: ScriptTemplateInput, key: string): string {
  return input.fields[key] ?? ''
}

function setField(setInput: ScriptTemplateFieldsProps['setInput'], key: string, value: string) {
  setInput((s) => ({ ...s, fields: { ...s.fields, [key]: value } }))
}

// ─── Fields UI ──────────────────────────────────────────────────────────────

interface EnumOption {
  id: string
  label: string
}

function EnumSelect({
  value,
  onChange,
  options,
}: {
  value: string
  onChange: (v: string) => void
  options: EnumOption[]
}) {
  return (
    <Select value={value} onValueChange={onChange}>
      <SelectTrigger>
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {options.map((o) => (
          <SelectItem key={o.id} value={o.id}>
            {o.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <Label>{label}</Label>
      {children}
    </div>
  )
}

function RequirementFields({ input, setInput }: ScriptTemplateFieldsProps) {
  const requirementType = (field(input, 'requirementType') || 'resources') as RequirementType

  switch (requirementType) {
    case 'resources':
      return (
        <>
          <Field label="Resource">
            <EnumSelect
              value={field(input, 'reqResourceId') || 'gold'}
              onChange={(v) => setField(setInput, 'reqResourceId', v)}
              options={BASIC_RESOURCE_IDS.map((r) => ({ id: r, label: r }))}
            />
          </Field>
          <Field label="Amount required">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'reqResourceAmount') || '0'}
              onChange={(e) => setField(setInput, 'reqResourceAmount', e.target.value)}
            />
          </Field>
        </>
      )
    case 'artifact':
      return (
        <Field label="Artifact to bring">
          <EntityCombobox
            value={field(input, 'reqArtifactSid')}
            onChange={(v) => setField(setInput, 'reqArtifactSid', v)}
            category="artifact"
            placeholder="Search artifacts…"
          />
        </Field>
      )
    case 'defeatMonster':
      return (
        <Field label="Neutral squad to defeat">
          <MapEntityCombobox
            value={field(input, 'reqSquadSid')}
            onChange={(v) => setField(setInput, 'reqSquadSid', v)}
            placeholder="Search placed squads…"
          />
        </Field>
      )
    case 'defeatHero':
      return (
        <Field label="Hero to defeat">
          <EntityCombobox
            value={field(input, 'reqHeroSid')}
            onChange={(v) => setField(setInput, 'reqHeroSid', v)}
            category="hero"
            placeholder="Search heroes…"
          />
        </Field>
      )
    case 'skill':
      return (
        <>
          <Field label="Primary skill">
            <EnumSelect
              value={field(input, 'reqSkill') || 'offence'}
              onChange={(v) => setField(setInput, 'reqSkill', v)}
              options={PRIMARY_SKILLS}
            />
          </Field>
          <Field label="Level required">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'reqSkillAmount') || '0'}
              onChange={(e) => setField(setInput, 'reqSkillAmount', e.target.value)}
            />
          </Field>
        </>
      )
  }
}

function RewardFields({ input, setInput }: ScriptTemplateFieldsProps) {
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType

  switch (rewardType) {
    case 'resources':
      return (
        <>
          <Field label="Resource">
            <EnumSelect
              value={field(input, 'rewardResourceId') || 'gold'}
              onChange={(v) => setField(setInput, 'rewardResourceId', v)}
              options={BASIC_RESOURCE_IDS.map((r) => ({ id: r, label: r }))}
            />
          </Field>
          <Field label="Amount given">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'rewardResourceAmount') || '0'}
              onChange={(e) => setField(setInput, 'rewardResourceAmount', e.target.value)}
            />
          </Field>
        </>
      )
    case 'artifact':
      return (
        <Field label="Artifact reward">
          <EntityCombobox
            value={field(input, 'rewardArtifactSid')}
            onChange={(v) => setField(setInput, 'rewardArtifactSid', v)}
            category="artifact"
            placeholder="Search artifacts…"
          />
        </Field>
      )
    case 'skill':
      return (
        <>
          <Field label="Primary skill">
            <EnumSelect
              value={field(input, 'rewardSkill') || 'offence'}
              onChange={(v) => setField(setInput, 'rewardSkill', v)}
              options={PRIMARY_SKILLS}
            />
          </Field>
          <Field label="Points given">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'rewardSkillAmount') || '0'}
              onChange={(e) => setField(setInput, 'rewardSkillAmount', e.target.value)}
            />
          </Field>
        </>
      )
  }
}

function renderFields(props: ScriptTemplateFieldsProps) {
  const { input, setInput } = props
  const requirementType = (field(input, 'requirementType') || 'resources') as RequirementType
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType

  return (
    <Fragment>
      <Field label="Seer's Hut object">
        <MapEntityCombobox
          value={field(input, 'hutSid')}
          onChange={(v) => setField(setInput, 'hutSid', v)}
          placeholder="Search placed objects…"
        />
      </Field>

      <Field label="Requirement">
        <EnumSelect
          value={requirementType}
          onChange={(v) => setField(setInput, 'requirementType', v)}
          options={REQUIREMENT_OPTIONS}
        />
      </Field>
      <RequirementFields {...props} />

      <Field label="Reward">
        <EnumSelect
          value={rewardType}
          onChange={(v) => setField(setInput, 'rewardType', v)}
          options={REWARD_OPTIONS}
        />
      </Field>
      <RewardFields {...props} />

      <Field label="Offer dialog (optional)">
        <Input
          value={field(input, 'offerDialogSid')}
          onChange={(e) => setField(setInput, 'offerDialogSid', e.target.value)}
          placeholder="Existing dialog SID shown on first visit"
        />
      </Field>
      <Field label="Reward dialog (optional)">
        <Input
          value={field(input, 'rewardDialogSid')}
          onChange={(e) => setField(setInput, 'rewardDialogSid', e.target.value)}
          placeholder="Existing dialog SID shown when the reward is granted"
        />
      </Field>
    </Fragment>
  )
}

// ─── Validate ───────────────────────────────────────────────────────────────

function validate(input: ScriptTemplateInput): string[] {
  const errors: string[] = []
  const hutSid = field(input, 'hutSid').trim()
  const requirementType = (field(input, 'requirementType') || 'resources') as RequirementType
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType

  if (!hutSid) errors.push("Pick the object acting as the Seer's Hut.")

  switch (requirementType) {
    case 'resources':
      if (!(Number(field(input, 'reqResourceAmount')) > 0)) errors.push('Set a positive required resource amount.')
      break
    case 'artifact':
      if (!field(input, 'reqArtifactSid').trim()) errors.push('Pick the artifact the hero must bring.')
      break
    case 'defeatMonster':
      if (!field(input, 'reqSquadSid').trim()) errors.push('Pick the neutral squad that must be defeated.')
      break
    case 'defeatHero':
      if (!field(input, 'reqHeroSid').trim()) errors.push('Pick the hero that must be defeated.')
      break
    case 'skill':
      if (!(Number(field(input, 'reqSkillAmount')) > 0)) errors.push('Set a positive required skill level.')
      break
  }

  switch (rewardType) {
    case 'resources':
      if (!(Number(field(input, 'rewardResourceAmount')) > 0)) errors.push('Set a positive reward resource amount.')
      break
    case 'artifact':
      if (!field(input, 'rewardArtifactSid').trim()) errors.push('Pick the artifact reward.')
      break
    case 'skill':
      if (!(Number(field(input, 'rewardSkillAmount')) > 0)) errors.push('Set a positive reward skill amount.')
      break
  }

  return errors
}

// ─── Generate ───────────────────────────────────────────────────────────────

function generate(input: ScriptTemplateInput, existingSids: { quests: string[] }) {
  const hutSid = field(input, 'hutSid').trim()
  const requirementType = (field(input, 'requirementType') || 'resources') as RequirementType
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType

  let requirementCondition: Condition
  const consumeActions: Action[] = []

  switch (requirementType) {
    case 'resources': {
      const resource = field(input, 'reqResourceId') || 'gold'
      const amount = String(Number(field(input, 'reqResourceAmount')) || 0)
      requirementCondition = { c: 'ResCounter', p: [resource, '>=', amount] }
      consumeActions.push({ a: 'RemoveRes', p: [resource, amount] })
      break
    }
    case 'artifact': {
      const artifactSid = field(input, 'reqArtifactSid').trim()
      requirementCondition = { c: 'ItemOwnSide', p: [artifactSid, '>=', '1'] }
      consumeActions.push({ a: 'RemoveItem', p: [artifactSid] })
      break
    }
    case 'defeatMonster':
      requirementCondition = { c: 'SquadKill', p: [field(input, 'reqSquadSid').trim(), ''] }
      break
    case 'defeatHero':
      requirementCondition = { c: 'HeroKill', p: [field(input, 'reqHeroSid').trim()] }
      break
    case 'skill': {
      const skill = field(input, 'reqSkill') || 'offence'
      const amount = String(Number(field(input, 'reqSkillAmount')) || 0)
      // Blank hero SID = whichever hero is currently involved, matching
      // ObjectInteractionAfter's own "leave blank for any hero" convention.
      requirementCondition = { c: 'HeroStat', p: ['', skill, '>=', amount] }
      break
    }
  }

  let rewardAction: Action
  switch (rewardType) {
    case 'resources': {
      const resource = field(input, 'rewardResourceId') || 'gold'
      const amount = String(Number(field(input, 'rewardResourceAmount')) || 0)
      rewardAction = { a: 'GiveRes', p: [resource, amount] }
      break
    }
    case 'artifact':
      rewardAction = { a: 'GiveItemHero', p: [field(input, 'rewardArtifactSid').trim(), ''] }
      break
    case 'skill': {
      const skill = field(input, 'rewardSkill') || 'offence'
      const amount = String(Number(field(input, 'rewardSkillAmount')) || 0)
      rewardAction = { a: 'GiveStatsHero', p: [skill, '', amount] }
      break
    }
  }

  const triggers: Trigger[] = []

  const offerDialogSid = field(input, 'offerDialogSid').trim()
  if (offerDialogSid) {
    triggers.push({
      conditions: [{ c: 'ObjectInteractionAfter', p: [hutSid, ''] }],
      actions: [{ a: 'Dialog', p: [offerDialogSid] }],
    })
  }

  const rewardDialogSid = field(input, 'rewardDialogSid').trim()
  triggers.push({
    conditionsLogic: 'And',
    conditions: [{ c: 'ObjectInteractionAfter', p: [hutSid, ''] }, requirementCondition],
    actions: [
      ...consumeActions,
      rewardAction,
      ...(rewardDialogSid ? [{ a: 'Dialog', p: [rewardDialogSid] } as Action] : []),
    ],
  })

  const subQuest: SubQuest = {
    sid: '1',
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    triggers,
  }

  const sid = existingSids.quests.includes(BASE_QUEST_SID)
    ? uniqueSid(BASE_QUEST_SID, existingSids.quests)
    : BASE_QUEST_SID

  const quest: Quest = {
    sid,
    hidden: true,
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    subQuests: [subQuest],
  }

  return { quest }
}

export const seersHutTemplate: ScriptTemplateDef = {
  id: 'seers-hut',
  name: "Seer's Hut",
  description:
    "Offers a quest at a chosen object: bring resources/an artifact, or defeat a monster/hero, or reach a skill level — then grants a reward once a hero returns having met it.",
  category: 'Classic HoMM3 Objects',
  slots: [],
  renderFields,
  validate: (input) => validate(input),
  generate: (input, _mapContext, existingSids) => generate(input, existingSids),
}
