// ─── Script Template: The Sphinx (issue #149) ─────────────────────────────────
// HoMM3.5/WoG's Sphinx prompted the player to TYPE a free-text answer to a
// riddle. Verified exhaustively that this is categorically impossible here:
// the dialog system's `DialogAnswer[]` is always a fixed, pre-authored,
// finite set of choices (confirmed against all shipped dialog content — no
// text-capture field exists anywhere), there is no condition/action
// primitive anywhere for player-typed input, `Counter` only stores numbers
// (no string-variable type exists in the scenario schema at all), Unfrozen's
// own mapmaking guide never mentions the concept, and the base game's own
// data has zero trace of a native Sphinx mechanic.
//
// This template instead builds a MULTIPLE-CHOICE riddle: the map author
// writes the question, the correct answer, and one or more wrong-answer
// decoys, each becoming its own DialogAnswer button. Reward/penalty fire per
// button via the dialog system's own branching — no Counter workaround is
// needed for the "check the answer" logic at all, since picking an answer
// *is* the branch natively. This is the first template to generate a new
// DialogFlow plus new localization tokens (every prior template only ever
// referenced dialogs/text the map author had already authored elsewhere).
//
// One real constraint: the "combat" penalty spawns a neutral squad at a
// NODE INDEX baked into the (possibly shared, multi-Sphinx) dialog at
// generation time. With more than one Sphinx, the squad would always spawn
// at whichever Sphinx was used to resolve that position, not necessarily
// the one actually visited — so the combat penalty is restricted to exactly
// one Sphinx per template application (validated below); the resource-loss
// penalty has no such restriction and supports any number of Sphinxes.

import { Fragment } from 'react'
import type { Quest, SubQuest, Trigger, Action } from '@/types/scenario'
import type { DialogFlow, DialogAnswer } from '@/types/dialog'
import type { ScriptTemplateDef, ScriptTemplateInput, ScriptTemplateFieldsProps } from '@/types/script-template'
import { uniqueSid } from '@/store/useScenarioStore'
import { resolveNodeForSid } from './resolve-node'
import { BASIC_RESOURCE_IDS } from '@/lib/resources'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select'
import EntityCombobox from '@/components/common/EntityCombobox'
import EntityPickerList from '@/components/common/EntityPickerList'
import StringListEditor from '@/components/common/StringListEditor'

const GENERATED_COMMENT = 'Generated by Script Template: Sphinx (v1)'
const BASE_QUEST_SID = 'script_sphinx'
const BASE_DIALOG_SID = 'script_sphinx_riddle'

const PRIMARY_SKILLS = [
  { id: 'offence', label: 'Attack' },
  { id: 'defence', label: 'Defense' },
  { id: 'spellPower', label: 'Spell Power' },
  { id: 'intelligence', label: 'Knowledge' },
]

type RewardType = 'resources' | 'artifact' | 'skill'
type PenaltyType = 'resources' | 'combat'

function field(input: ScriptTemplateInput, key: string): string {
  return (input.fields[key] ?? '').trim()
}

function setField(setInput: ScriptTemplateFieldsProps['setInput'], key: string, value: string) {
  setInput((s) => ({ ...s, fields: { ...s.fields, [key]: value } }))
}

function sphinxes(input: ScriptTemplateInput): string[] {
  return (input.slots.sphinxes ?? []).filter((s) => s.trim() !== '')
}

function wrongAnswers(input: ScriptTemplateInput): string[] {
  return (input.slots.wrongAnswers ?? []).filter((s) => s.trim() !== '')
}

// ─── Fields UI ──────────────────────────────────────────────────────────────

interface EnumOption {
  id: string
  label: string
}

function EnumSelect({ value, onChange, options }: { value: string; onChange: (v: string) => void; options: EnumOption[] }) {
  return (
    <Select value={value} onValueChange={onChange}>
      <SelectTrigger>
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {options.map((o) => (
          <SelectItem key={o.id} value={o.id}>
            {o.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <Label>{label}</Label>
      {children}
    </div>
  )
}

const REWARD_OPTIONS: EnumOption[] = [
  { id: 'resources', label: 'Give Resources' },
  { id: 'artifact', label: 'Give Artifact' },
  { id: 'skill', label: 'Boost a Primary Skill' },
]

const PENALTY_OPTIONS: EnumOption[] = [
  { id: 'resources', label: 'Lose Resources' },
  { id: 'combat', label: 'Combat vs. Neutral Monsters' },
]

function RewardFields({ input, setInput }: ScriptTemplateFieldsProps) {
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType
  switch (rewardType) {
    case 'resources':
      return (
        <>
          <Field label="Resource">
            <EnumSelect
              value={field(input, 'rewardResourceId') || 'gold'}
              onChange={(v) => setField(setInput, 'rewardResourceId', v)}
              options={BASIC_RESOURCE_IDS.map((r) => ({ id: r, label: r }))}
            />
          </Field>
          <Field label="Amount given">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'rewardResourceAmount') || '0'}
              onChange={(e) => setField(setInput, 'rewardResourceAmount', e.target.value)}
            />
          </Field>
        </>
      )
    case 'artifact':
      return (
        <Field label="Artifact reward">
          <EntityCombobox
            value={field(input, 'rewardArtifactSid')}
            onChange={(v) => setField(setInput, 'rewardArtifactSid', v)}
            category="artifact"
            placeholder="Search artifacts…"
          />
        </Field>
      )
    case 'skill':
      return (
        <>
          <Field label="Primary skill">
            <EnumSelect
              value={field(input, 'rewardSkill') || 'offence'}
              onChange={(v) => setField(setInput, 'rewardSkill', v)}
              options={PRIMARY_SKILLS}
            />
          </Field>
          <Field label="Points given">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'rewardSkillAmount') || '0'}
              onChange={(e) => setField(setInput, 'rewardSkillAmount', e.target.value)}
            />
          </Field>
        </>
      )
  }
}

function PenaltyFields({ input, setInput }: ScriptTemplateFieldsProps) {
  const penaltyType = (field(input, 'penaltyType') || 'resources') as PenaltyType
  switch (penaltyType) {
    case 'resources':
      return (
        <>
          <Field label="Resource">
            <EnumSelect
              value={field(input, 'penaltyResourceId') || 'gold'}
              onChange={(v) => setField(setInput, 'penaltyResourceId', v)}
              options={BASIC_RESOURCE_IDS.map((r) => ({ id: r, label: r }))}
            />
          </Field>
          <Field label="Amount lost">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'penaltyResourceAmount') || '0'}
              onChange={(e) => setField(setInput, 'penaltyResourceAmount', e.target.value)}
            />
          </Field>
        </>
      )
    case 'combat':
      return (
        <>
          <Field label="Neutral squad template">
            <EntityCombobox
              value={field(input, 'penaltySquadSid')}
              onChange={(v) => setField(setInput, 'penaltySquadSid', v)}
              category="squadTemplate"
              placeholder="Search squad templates…"
            />
          </Field>
          <Field label="Squad strength">
            <Input
              type="number"
              className="w-32"
              value={field(input, 'penaltySquadStrength') || '1000'}
              onChange={(e) => setField(setInput, 'penaltySquadStrength', e.target.value)}
            />
          </Field>
          <p className="text-xs text-muted-foreground">
            Requires exactly one Sphinx object — the squad's spawn location is fixed at generation
            time, so multiple Sphinxes sharing this riddle would all spawn it in the same place.
          </p>
        </>
      )
  }
}

function renderFields(props: ScriptTemplateFieldsProps) {
  const { input, setInput } = props
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType
  const penaltyType = (field(input, 'penaltyType') || 'resources') as PenaltyType

  return (
    <Fragment>
      <Field label="Sphinx objects">
        <EntityPickerList
          values={input.slots.sphinxes ?? ['']}
          onChange={(values) => setInput((s) => ({ ...s, slots: { ...s.slots, sphinxes: values } }))}
          addLabel="+ Add sphinx object"
          placeholder="Search placed objects…"
        />
      </Field>

      <Field label="Riddle text">
        <Textarea
          value={field(input, 'riddleText')}
          onChange={(e) => setField(setInput, 'riddleText', e.target.value)}
          placeholder="What has a voice but no mouth, and speaks only when spoken to?"
          rows={3}
        />
      </Field>

      <Field label="Correct answer">
        <Input
          value={field(input, 'correctAnswerText')}
          onChange={(e) => setField(setInput, 'correctAnswerText', e.target.value)}
          placeholder="e.g. An echo"
        />
      </Field>

      <Field label="Wrong answers (decoys)">
        <StringListEditor
          values={input.slots.wrongAnswers ?? ['']}
          onChange={(values) => setInput((s) => ({ ...s, slots: { ...s.slots, wrongAnswers: values } }))}
          addLabel="+ Add wrong answer"
          placeholder="A plausible-sounding wrong answer"
        />
      </Field>

      <Field label="Reward">
        <EnumSelect value={rewardType} onChange={(v) => setField(setInput, 'rewardType', v)} options={REWARD_OPTIONS} />
      </Field>
      <RewardFields {...props} />

      <Field label="Penalty">
        <EnumSelect value={penaltyType} onChange={(v) => setField(setInput, 'penaltyType', v)} options={PENALTY_OPTIONS} />
      </Field>
      <PenaltyFields {...props} />
    </Fragment>
  )
}

// ─── Validate ───────────────────────────────────────────────────────────────

function validate(input: ScriptTemplateInput, mapContext: import('@/types/map-context').MapContext | null): string[] {
  const errors: string[] = []
  const sphinxList = sphinxes(input)
  const wrongList = wrongAnswers(input)
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType
  const penaltyType = (field(input, 'penaltyType') || 'resources') as PenaltyType

  if (sphinxList.length === 0) errors.push('Pick at least one Sphinx object.')
  if (!field(input, 'riddleText')) errors.push('Write the riddle text.')
  if (!field(input, 'correctAnswerText')) errors.push('Write the correct answer.')
  if (wrongList.length === 0) errors.push('Add at least one wrong-answer decoy.')

  switch (rewardType) {
    case 'resources':
      if (!(Number(field(input, 'rewardResourceAmount')) > 0)) errors.push('Set a positive reward resource amount.')
      break
    case 'artifact':
      if (!field(input, 'rewardArtifactSid')) errors.push('Pick the artifact reward.')
      break
    case 'skill':
      if (!(Number(field(input, 'rewardSkillAmount')) > 0)) errors.push('Set a positive reward skill amount.')
      break
  }

  switch (penaltyType) {
    case 'resources':
      if (!(Number(field(input, 'penaltyResourceAmount')) > 0)) errors.push('Set a positive penalty resource amount.')
      break
    case 'combat':
      if (!field(input, 'penaltySquadSid')) errors.push('Pick the neutral squad template for the combat penalty.')
      if (!(Number(field(input, 'penaltySquadStrength')) > 0)) errors.push('Set a positive squad strength.')
      if (sphinxList.length > 1) {
        errors.push(
          "The combat penalty only supports exactly one Sphinx object — remove extra Sphinxes or switch to the resource-loss penalty.",
        )
      }
      if (!mapContext) {
        errors.push('Load a .map file to resolve the Sphinx position for the combat penalty.')
      } else if (sphinxList.length === 1 && resolveNodeForSid(sphinxList[0], mapContext) === undefined) {
        errors.push(`Could not resolve a map position for Sphinx object "${sphinxList[0]}".`)
      }
      break
  }

  return errors
}

// ─── Generate ───────────────────────────────────────────────────────────────

function generate(
  input: ScriptTemplateInput,
  mapContext: import('@/types/map-context').MapContext | null,
  existingSids: { quests: string[]; dialogs: string[] },
) {
  const sphinxList = sphinxes(input)
  const wrongList = wrongAnswers(input)
  const rewardType = (field(input, 'rewardType') || 'resources') as RewardType
  const penaltyType = (field(input, 'penaltyType') || 'resources') as PenaltyType

  const dialogSid = existingSids.dialogs.includes(BASE_DIALOG_SID)
    ? uniqueSid(BASE_DIALOG_SID, existingSids.dialogs)
    : BASE_DIALOG_SID

  const riddleTextSid = `${dialogSid}_text`
  const correctAnswerSid = `${dialogSid}_correct`
  const localizationTokens: Record<string, string> = {
    [riddleTextSid]: field(input, 'riddleText'),
    [correctAnswerSid]: field(input, 'correctAnswerText'),
  }

  let rewardAction: Action
  switch (rewardType) {
    case 'resources': {
      const resource = field(input, 'rewardResourceId') || 'gold'
      const amount = String(Number(field(input, 'rewardResourceAmount')) || 0)
      rewardAction = { a: 'GiveRes', p: [resource, amount] }
      break
    }
    case 'artifact':
      rewardAction = { a: 'GiveItemHero', p: [field(input, 'rewardArtifactSid'), ''] }
      break
    case 'skill': {
      const skill = field(input, 'rewardSkill') || 'offence'
      const amount = String(Number(field(input, 'rewardSkillAmount')) || 0)
      rewardAction = { a: 'GiveStatsHero', p: [skill, '', amount] }
      break
    }
  }

  let penaltyActions: Action[] = []
  switch (penaltyType) {
    case 'resources': {
      const resource = field(input, 'penaltyResourceId') || 'gold'
      const amount = String(Number(field(input, 'penaltyResourceAmount')) || 0)
      penaltyActions = [{ a: 'RemoveRes', p: [resource, amount] }]
      break
    }
    case 'combat': {
      const squadSid = field(input, 'penaltySquadSid')
      const strength = String(Number(field(input, 'penaltySquadStrength')) || 0)
      const node = mapContext ? resolveNodeForSid(sphinxList[0], mapContext) : undefined
      if (node !== undefined) {
        const spawnedEntitySid = `${dialogSid}_penalty_squad`
        penaltyActions = [
          { a: 'SpawnSquadNPC', p: [squadSid, String(node), strength, 'true', spawnedEntitySid] },
          { a: 'InitiateAttack', p: [spawnedEntitySid] },
        ]
      }
      break
    }
  }

  const correctAnswer: DialogAnswer = {
    text: correctAnswerSid,
    actions: [{ a: 'End', p: [] }],
    mapActions: [rewardAction],
  }

  const wrongDialogAnswers: DialogAnswer[] = wrongList.map((text, i) => {
    const sid = `${dialogSid}_wrong_${i}`
    localizationTokens[sid] = text
    return {
      text: sid,
      actions: [{ a: 'End', p: [] }],
      mapActions: penaltyActions,
    }
  })

  const dialogFlow: DialogFlow = {
    id: dialogSid,
    slides: [
      {
        id: 'riddle',
        text: riddleTextSid,
        answers: [correctAnswer, ...wrongDialogAnswers],
      },
    ],
  }

  const triggers: Trigger[] = sphinxList.map((sphinxSid) => ({
    repeat: true,
    conditions: [{ c: 'ObjectInteractionAfter', p: [sphinxSid, ''] }],
    actions: [{ a: 'Dialog', p: [dialogSid] }],
  }))

  const subQuest: SubQuest = {
    sid: '1',
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    triggers,
  }

  const questSid = existingSids.quests.includes(BASE_QUEST_SID)
    ? uniqueSid(BASE_QUEST_SID, existingSids.quests)
    : BASE_QUEST_SID

  const quest: Quest = {
    sid: questSid,
    hidden: true,
    activeOnStart: true,
    comment: GENERATED_COMMENT,
    subQuests: [subQuest],
  }

  return { quest, dialogFlow, localizationTokens }
}

export const sphinxTemplate: ScriptTemplateDef = {
  id: 'sphinx',
  name: 'The Sphinx',
  description:
    "A multiple-choice riddle — pick a correct answer and decoys, then the reward and penalty. True free-text input isn't possible in this engine (verified exhaustively); this is the closest faithful equivalent, using the dialog system's own answer branching.",
  category: 'Classic HoMM3 Objects',
  slots: [],
  renderFields,
  validate: (input, mapContext) => validate(input, mapContext),
  generate: (input, mapContext, existingSids) => generate(input, mapContext, existingSids),
}
