string current_specialization_unfrozen_hero_7_spec_bonus
{
	Text( return, "1" )
}

string current_specialization_unfrozen_hero_7_spec_increment
{
	Text( return, "1" )
}

string current_specialization_unfrozen_hero_7_spec_level_step
{
	Text( return, "10" )
}

//

string current_specialization_unfrozen_hero_8_spec_bonus
{
	Text( return, "1" )
}

string current_specialization_unfrozen_hero_8_spec_level_step
{
	Text( return, "2" )
}

//

string current_specialization_unfrozen_hero_14_spec_bonus
{
	Text( return, "10" )
}

string current_specialization_unfrozen_hero_14_spec_bonus_alt
{
	Text( return, "1" )
}

string current_specialization_unfrozen_hero_14_spec_increment
{
	Text( return, "5" )
}

string current_specialization_unfrozen_hero_14_spec_level_step
{
	Text( return, "6" )
}

//

string current_specialization_unfrozen_hero_17_bonus
{
	Text( return, "50" )
}

//

string current_specialization_unfrozen_hero_18_spec_bonus
{
	Text( return, "1" )
}

string current_specialization_unfrozen_hero_18_spec_increment
{
	Text( return, "1" )
}

string current_specialization_unfrozen_hero_18_spec_level_step
{
	Text( return, "8" )
}