string campaign_hero_1_name
{ 
	LocSid ( heroName, "campaign_hero_1" )

	Text ( return, heroName )
}

string campaign_hero_2_name
{ 
	LocSid ( heroName, "campaign_hero_2" )

	Text ( return, heroName )
}

string campaign_hero_3_name
{ 
	LocSid ( heroName, "campaign_hero_3" )

	Text ( return, heroName )
}

string campaign_hero_4_name
{ 
	LocSid ( heroName, "campaign_hero_4" )

	Text ( return, heroName )
}
